name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'index.html'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up GitHub Pages
        uses: actions/configure-pages@v3
        with:
          static_site_generator: none

      - name: Upload artifacts
        uses: actions/upload-pages-artifact@v1
        with:
          path: './'

      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v1
